### ISSUE TITLE
Pkgtool.exe Unhandled Exception: System.ArgumentException

### ISSUE THREAD

**Issue by opoisso893** [maxton/LibOrbisPkg#25]
when using pkgtool.exe extractpkg <input.pkg> "passcode" <output_directory> I get error message:
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at GameArchives.Local.LocalDirectory..ctor(String path) in C:\.......\LibOrbisPkg-master\GameArchives Library\Local\LocalDirectory.cs:line 44
Do you have any idea?

**Comment by opoisso893** [comment]
I didn't miss passcode. First post edited.

**Comment by opoisso893** [comment]
It's ok now. I didn't put the complete path of input.pkg because file was in same directory as pkgtool.exe
My command line was:
pkgtool.exe extractpkg EPxxxx-CUSAxxxxx_00-....... 000000000000000000000000000000 c:\temp

**Comment by opoisso893** [comment]
Also using .\input.pkg is working so it's perfect.
Thanks for your help
