### ISSUE TITLE
PKG build error: "Length of the data to encrypt is invalid"

### ISSUE THREAD

**Issue by maxton** [maxton/LibOrbisPkg#29]
Look into this
Converting "Yellow Ledbetter - Pearl Jam" CON in LibForge
```
Unhandled Exception: System.Security.Cryptography.CryptographicException: Length of the data to encrypt is invalid.
   at System.Security.Cryptography.RijndaelManagedTransform.EncryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at LibOrbisPkg.Util.Crypto.AesCbcCfb128Encrypt(Byte[] out, Byte[] in, Int32 size, Byte[] key, Byte[] iv)
   at LibOrbisPkg.PKG.PkgWriter.WriteBody(Pkg pkg, String contentId, String passcode)
   at LibOrbisPkg.PKG.PkgBuilder.Write(Stream s, Action`1 Logger)
   at LibForge.Util.PkgCreator.BuildPkg(String proj, String outPath)
   at ForgeTool.Program.Main(String[] args)
```

**Comment by maxton** [comment]
Couldn't reproduce this, even on 0.1.143
