### ISSUE TITLE
LibOrbisPkg/PkgTool fails to extract inner PSF/file from fake PKG

### ISSUE THREAD

**Issue by Kein** [maxton/LibOrbisPkg#47]
Build from git as of 03.01.2019 and testing on FF7 Re Demo pkg.

Here is **validate** and **listentries** output:
https://pastebin.com/raw/MWWMeTvP
https://pastebin.com/raw/X5Xm4a7S

An attempt to **extract** fails:
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'count')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at LibOrbisPkg.PFS.PfsReader.LoadDir(UInt32 dinode, Dir parent, String name)
   at LibOrbisPkg.PFS.PfsReader..ctor(IMemoryReader r, UInt64 pfs_flags, Byte[] ekpfs)
   at LibOrbisPkg.PFS.PfsReader..ctor(MemoryMappedViewAccessor r, UInt64 pfs_flags, Byte[] ekpfs)
   at PkgTool.Program.<>c.<.cctor>b__6_4(Dictionary`2 flags, Dictionary`2 optionals, String[] args)
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name)
   at PkgTool.Program.Main(String[] args)
```

Let me know if any debug data is needed.

**Comment by maxton** [comment]
That error is due to corrupt inodes. Given the hashes are valid, you probably just have the wrong passcode.

**Comment by Kein** [comment]
The fake repackaged one does not require passcode. It extract 98% of the content but the last file is corrupt
