### ISSUE TITLE
Unknown SFO type: 0000

### ISSUE THREAD

**Issue by Pysis868** [maxton/LibOrbisPkg#49]
> PkgTool.exe sfo_listentries param.sfo

Unhandled Exception: System.Exception: Unknown SFO type: 0000
   at LibOrbisPkg.SFO.ParamSfo.FromStream(Stream s)
   at PkgTool.Program.<>c.<.cctor>b__6_11(String[] args)
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name)
   at PkgTool.Program.Main(String[] args)

**Comment by maxton** [comment]
Can you attach an SFO file that reproduces this error?

**Comment by Pysis868** [comment]
https://drive.google.com/open?id=1BLx5TFXsdTu-OM2Xw3m8pYcFs306Tapk

### Disc File
`/mnt/disc/bd/param.sfo`
```
~> file ...
...\param.sfo: data

~> md5sum.exe (getclip)
\c36e7ef2f9e0179628125a48fc366b78 *...\\param.sfo

~> xxd ... | head
00000000: 5343 4543 4446 0000 0100 0000 0100 0000  SCECDF..........
00000010: 0100 0000 0000 0000 0000 0000 0000 0000  ................
00000020: 0200 0000 0000 0000 c809 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 d001 0000 0000 0000  ................
00000040: 3004 0000 0000 0000 0100 21c2 907c 5710  0.........!..|W.
00000050: 2e8e eece e88e 7b60 07e3 048c 74f2 0239  ......{`....t..9
00000060: a2e1 0bcb 8238 20ee e7aa ffff 0000 0000  .....8 .........
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0100 0000 0000 0000 0008 0000 0000 0000  ................
00000090: c801 0000 0000 0000 0100 24de 2266 3815  ..........$."f8.
```

### Possibly corresponding Dump File
`CUSA05630-app\sce_sys\param.sfo`
```
~> file ...
...\CUSA05630-app\sce_sys\param.sfo: data

md5sum.exe (getclip)
\663bc27eba9cfd5b2f68b810d650a9b6 *...\\CUSA05630-app\\sce_sys\\param.sfo

~> xxd ... | head
00000000: 0050 5346 0101 0000 9401 0000 0003 0000  .PSF............
00000010: 1800 0000 0000 0404 0400 0000 0400 0000  ................
00000020: 0000 0000 0900 0402 0600 0000 0800 0000  ................
00000030: 0400 0000 1100 0404 0400 0000 0400 0000  ................
00000040: 0c00 0000 1b00 0404 0400 0000 0400 0000  ................
00000050: 1000 0000 2600 0402 0300 0000 0400 0000  ....&...........
00000060: 1400 0000 2f00 0402 2500 0000 3000 0000  ..../...%...0...
00000070: 1800 0000 3a00 0404 0400 0000 0400 0000  ....:...........
00000080: 4800 0000 4300 0404 0400 0000 0400 0000  H...C...........
00000090: 4c00 0000 5600 0402 0400 0000 0400 0000  L...V...........
```

**Comment by maxton** [comment]
Oh, that is a Blu-ray SFO. It's kind of out of the scope of this project, but I have added read support for it anyway.
