### ISSUE TITLE
PkgTool-0.1.224 - pkg_build error

### ISSUE THREAD

**Issue by tomazzz369z** [maxton/LibOrbisPkg#55]
i can't build any package with latest version

PkgTool-0.1.224 - error:

Preparing inner PFS...
 [innerpfs] Setting up filesystem structure...
 [innerpfs] Creating inodes (1 dirs and 0 files)...
 [innerpfs] Calculating data block layout...
Preparing outer PFS...
 [outerpfs] Setting up filesystem structure...
 [outerpfs] Creating inodes (0 dirs and 1 files)...
 [outerpfs] Calculating data block layout...
Preparing PKG header and body...

Unhandled Exception: System.Security.Cryptography.CryptographicException: Invalid signature.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._ImportKey(SafeProvHandle hCSP, Int32 keyNumber, CspProviderFlags flags, Object cspObject, SafeKeyHandle& hKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
   at LibOrbisPkg.Util.Crypto.RSA2048SignSha256(Byte[] sha256Hash, RSAKeyset keyset)
   at LibOrbisPkg.Rif.LicenseDat.Sign()
   at LibOrbisPkg.Rif.LicenseDat..ctor(String ContentId, ContentType contentType, Byte[] EntitlementKey)
   at LibOrbisPkg.PKG.PkgBuilder.GenLicense()
   at LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   at LibOrbisPkg.PKG.PkgBuilder.InitPkg()
   at LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   at PkgTool.Program.<>c.<.cctor>b__6_2(String[] args)
   at PkgTool.Verb.<>c__DisplayClass4_0.<Create>b__0(Dictionary`2 _, Dictionary`2 _2, String[] a)
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name)
   at PkgTool.Program.Main(String[] args)

PkgTool-0.1.223 - ok:

Preparing inner PFS...
 [innerpfs] Setting up filesystem structure...
 [innerpfs] Creating inodes (1 dirs and 0 files)...
 [innerpfs] Calculating data block layout...
Preparing outer PFS...
 [outerpfs] Setting up filesystem structure...
 [outerpfs] Creating inodes (0 dirs and 1 files)...
 [outerpfs] Calculating data block layout...
Preparing PKG header and body...
 [outerpfs] Writing data...
 [innerpfs] Writing data...
 [outerpfs] Signing in parallel...
 [outerpfs] Encrypting in parallel...
Calculating SHA256 of finished outer PFS...

**Comment by maxton** [comment]
Unfortunately I cannot reproduce this. Are you on Windows 10?

**Comment by tomazzz369z** [comment]
win xp. try with this

https://www88.zippyshare.com/v/b8gxHnz6/file.html

regards

**Comment by tomazzz369z** [comment]
the same issue on windows 7

**Comment by maxton** [comment]
I'm not going to support anything lower than w10. Try updating your .net runtime.

**Comment by tomazzz369z** [comment]
ok, but based on source between PkgTool-0.1.223 and PkgTool-0.1.224 only keys are changed, so why app suddenly stopped working

regards

**Comment by maxton** [comment]
The dmp1 and dmq1 components of the key were wrong, and were causing the app to not work on Linux (.Net Core), which uses OpenSSL for cryptography. On windows it seems those components were ignored.

I don't know why older versions of windows are now rejecting the key, because OpenSSL has no issues with it and neither does windows 10.
