### ISSUE TITLE
Playgo Chunk hash file was not allocated enough space

### ISSUE THREAD

**Issue by NikolausC** [maxton/LibOrbisPkg#64]
When creating a pkg from a gp4, the following error is shown in the Log Window:

```
Preparing inner PFS...
 [innerpfs] Setting up filesystem structure...
 [innerpfs] Creating inodes (5 dirs and 29 files)...
 [innerpfs] Calculating data block layout...
Preparing outer PFS...
 [outerpfs] Setting up filesystem structure...
 [outerpfs] Creating inodes (0 dirs and 1 files)...
 [outerpfs] Calculating data block layout...
Preparing PKG header and body...
Error: System.Exception: Playgo Chunk hash file was not allocated enough space. Report this as a bug
   at LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   at LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   at PkgEditor.Views.GP4View.<>c__DisplayClass22_0.<buildPkg_Click>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PkgEditor.Views.GP4View.<buildPkg_Click>d__22.MoveNext()
   at LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   at LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   at PkgEditor.Views.GP4View.<>c__DisplayClass22_0.<buildPkg_Click>b__2()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PkgEditor.Views.GP4View.<buildPkg_Click>d__22.MoveNext()
```

**Comment by maxton** [comment]
Aw, I really thought I had fixed this particular bug. Can you attach a project that reproduces this error?

**Comment by alicepergatta** [comment]
I have same issue
Project - P5R.pkg, that cursed thing.
But i can build pkg succesfully if i remove/comment size comparsion check

**Comment by hippie68** [comment]
I got the same error today with PkgTool.Core! It said I should report this as a bug.
I extracted a PKG with "PkgTool.Core pkg_makegp4", then (without changing anything) I tried to rebuild it with "PkgTool.Core pkg_build", and then the error showed up.
[project.zip](https://github.com/maxton/LibOrbisPkg/files/5903248/project.zip)

**Comment by manuelx98** [comment]
Exact same error using PkgEditor to build a PKG from a GP4 project.
[Project.zip](https://github.com/maxton/LibOrbisPkg/files/7745791/Project.zip)

**Comment by ribamarsaraiva** [comment]
> Exact same error using PkgEditor to build a PKG from a GP4 project. [Project.zip](https://github.com/maxton/LibOrbisPkg/files/7745791/Project.zip)

build pkg using pkgeditor only work with 1 chunk, this problem must be because source pkg has more than 1 chunk inside.
