### ISSUE TITLE
Building  pkg_build on Ubuntu Docker Container Failing

### ISSUE THREAD

**Issue by futurepr0n** [maxton/LibOrbisPkg#69]
Hi, I am trying to build a docker container and when I run the PgkTool.Core-Linux I end up with an error I was hoping you might be able to help me with:

```
root@82a969ee48b5:/app/PkgTool.Core# ./PkgTool.Core pkg_build /app/OpenOrbis-PS4-Toolchain/samples/SDL2/pkg/pkg.gp4 .
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Reflection.RuntimeAssembly.GetLocale()
   at System.Reflection.RuntimeAssembly.GetName(Boolean)
   at System.Reflection.Assembly.GetName()
   at System.AppDomain.get_FriendlyName()
   at PkgTool.Program.Main(System.String[])
Aborted
```

Any chance you think you know what might help me to get passed that?

**Comment by maxton** [comment]
This is not a PkgTool issue, your system is missing some libraries. Check this
https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md#troubleshooting
