### ISSUE TITLE
"PkgTool.Core pkg_extract" won't extract

### ISSUE THREAD

**Issue by hippie68** [maxton/LibOrbisPkg#74]
While "PkgTool.Core pkg_makegp4" works fine (although not extracting certain files, like playgo files) I can't extract my PKGs with "PkgTool.Core pkg_extract" into an existing directory. It will error out like this:

```
PkgTool.Core pkg_extract /media/hippie68/super.pkg test
Unhandled exception. System.Exception: inode 0 is corrupt. 
   at LibOrbisPkg.PFS.PfsReader.LoadDir(UInt32 dinode, Dir parent, String name) in /home/hippie68/github/LibOrbisPkg/LibOrbisPkg/PFS/PfsReader.cs:line 207
   at LibOrbisPkg.PFS.PfsReader..ctor(IMemoryReader r, UInt64 pfs_flags, Byte[] ekpfs, Byte[] tweak, Byte[] data) in /home/hippie68/github/LibOrbisPkg/LibOrbisPkg/PFS/PfsReader.cs:line 168
   at LibOrbisPkg.PFS.PfsReader..ctor(MemoryMappedViewAccessor r, UInt64 pfs_flags, Byte[] ekpfs, Byte[] tweak, Byte[] data) in /home/hippie68/github/LibOrbisPkg/LibOrbisPkg/PFS/PfsReader.cs:line 113
   at PkgTool.Program.<>c.<.cctor>b__6_4(Dictionary`2 flags, Dictionary`2 optionals, String[] args) in /home/hippie68/github/LibOrbisPkg/PkgTool/Program.cs:line 123
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name) in /home/hippie68/github/LibOrbisPkg/PkgTool/Program.cs:line 706
   at PkgTool.Program.Main(String[] args) in /home/hippie68/github/LibOrbisPkg/PkgTool/Program.cs:line 20
Aborted
```

**Comment by maxton** [comment]
Uh, probably there was an issue decrypting the EKPFS. Did you ever try setting the passcode with `PkgTool.Core pkg_extract --passcode 00000000000000000000000000000000 super.pkg test`?

**Comment by hippie68** [comment]
No, I thought it would work like pkg_makegp4, not requiring the "zeroes" passcode. But now I tried it with your command and passcode, and then it does extract. Thanks!
